name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  avoid-reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel previous workflows"
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{secrets.TOKEN_GITHUB}}

  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node-version}}
          cache: "npm"

  lint:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: "Running Eslint"
        run: npm run lint

  test-suit:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: "Running test suit"
        run: npm run test:ci
      - name: "Checking coverage"
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 70

  build:
    runs-on: ubuntu-latest
    needs: [lint, test-suit]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: "Generating build"
        run: npm run build
